# Development Redis Setup
services:
  redis:
    image: redis:7-alpine
    container_name: openautomae-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: openautomae-redis-insight
    ports:
      - "8001:5540"
    volumes:
      - redis-insight-data:/db
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - RIPORT=8001

volumes:
  redis-data:
    driver: local
  redis-insight-data:
    driver: local