name: Deploy .NET API to Ubuntu

on:
  push:
    branches: [ develop, test-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Ensure JWT package version
      run: |
        dotnet add OpenAutomate.API/OpenAutomate.API.csproj package System.IdentityModel.Tokens.Jwt --version 8.0.0
        dotnet restore
      
    - name: Build app
      run: dotnet build --configuration Release --no-restore

    - name: Publish app
      run: dotnet publish -c Release -o publish --no-restore

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "publish/**"
        target: "${{ secrets.DEPLOY_PATH }}/app"

    - name: Restart service on server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo systemctl restart myapi
