name: SonarQube Analysis

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:  # Allow manual triggering

env:
  SONAR_PROJECT_KEY: openautomate-backend
  SONAR_PROJECT_NAME: openautomate-backend
  SONAR_HOST_URL: http://sonar.openautomate.me
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

jobs:
  sonar:
    name: SonarQube Analysis with Code Coverage
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history for better SonarQube analysis
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for accurate blame information

      # Step 2: Set up .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # Step 3: Setup Java (required for SonarScanner)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 4: Install SonarQube Scanner
      - name: Install SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global coverlet.console
      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      # Step 5: Cache SonarQube packages
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/*.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Step 6: Begin SonarQube analysis
      - name: Begin SonarQube analysis
        run: |
          dotnet sonarscanner begin \
            /k:"$SONAR_PROJECT_KEY" \
            /n:"$SONAR_PROJECT_NAME" \
            /d:sonar.host.url="$SONAR_HOST_URL" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths="./TestResults/*.opencover.xml,**/*.opencover.xml" \
            /d:sonar.cs.vstest.reportsPaths="./TestResults/**/*.trx" \
            /d:sonar.coverage.exclusions="**/*Tests*.cs,**/*.Tests/**,**/*Tests*/**,**/obj/**/*,**/*.designer.cs,**/Migrations/**" \
            /d:sonar.exclusions="**/bin/**/*,**/obj/**/*,**/*.Tests/**/*,**/*Tests*/**/*" \
            /d:sonar.cpd.exclusions="**/Migrations/**/*" \
            /d:sonar.verbose=true

      # Step 7: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore OpenAutomate.Backend.sln

      # Step 8: Build the solution
      - name: Build solution
        run: dotnet build OpenAutomate.Backend.sln --configuration Release --no-restore

      # Step 9: Run tests with coverage (proper project targeting)
      - name: Run tests with coverage
        run: |
          # Create a directory for the results
          mkdir -p ./TestResults
          
          # Run Core tests
          dotnet test OpenAutomate.Core.Tests/OpenAutomate.Core.Tests.csproj \
            --configuration Release \
            --no-build \
            --logger:trx \
            --results-directory:./TestResults \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            '/p:Include=[OpenAutomate.Core]*'

          # Run API tests
          dotnet test OpenAutomate.API.Tests/OpenAutomate.API.Tests.csproj \
            --configuration Release \
            --no-build \
            --logger:trx \
            --results-directory:./TestResults \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            '/p:Include=[OpenAutomate.API]*'
          
          # Run Infrastructure tests
          dotnet test OpenAutomate.Infrastructure.Tests/OpenAutomate.Infrastructure.Tests.csproj \
            --configuration Release \
            --no-build \
            --logger:trx \
            --results-directory:./TestResults \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            '/p:Include=[OpenAutomate.Infrastructure]*'
          
          # Check for coverage files in test project directories
          echo "Looking for coverage files in test project directories:"
          find . -name "*.opencover.xml" -type f
          
          # Copy coverage files from test project directories to TestResults
          echo "Copying coverage files from test project directories to TestResults"
          mkdir -p ./TestResults
          
          if [ -f "./OpenAutomate.Core.Tests/coverage.opencover.xml" ]; then
            cp ./OpenAutomate.Core.Tests/coverage.opencover.xml ./TestResults/core.coverage.opencover.xml
          fi
          
          if [ -f "./OpenAutomate.API.Tests/coverage.opencover.xml" ]; then
            cp ./OpenAutomate.API.Tests/coverage.opencover.xml ./TestResults/api.coverage.opencover.xml
          fi
          
          if [ -f "./OpenAutomate.Infrastructure.Tests/coverage.opencover.xml" ]; then
            cp ./OpenAutomate.Infrastructure.Tests/coverage.opencover.xml ./TestResults/infrastructure.coverage.opencover.xml
          fi
          
          # List files in TestResults directory after copying
          echo "Files in TestResults directory after copying:"
          ls -la ./TestResults/ || echo "TestResults directory is empty"
          
          # Install reportgenerator for merging reports
          dotnet tool install -g dotnet-reportgenerator-globaltool || true
          
          # Merge all coverage reports into one
          echo "Merging coverage reports"
          reportgenerator \
            -reports:"./TestResults/*.opencover.xml" \
            -targetdir:"./TestResults/CoverageReport" \
            -reporttypes:Opencover \
            -assemblyfilters:"+OpenAutomate.API;+OpenAutomate.Core;+OpenAutomate.Infrastructure"
          
          # Copy the merged report to the expected location
          cp -f ./TestResults/CoverageReport/Opencover.xml ./TestResults/coverage.opencover.xml || true
          
          # List files after merging
          echo "Files after merging:"
          ls -la ./TestResults/ || echo "TestResults directory is empty"

      # List coverage files for debugging
      - name: List coverage files
        run: |
          echo "=== Checking coverage files ==="
          echo "In TestResults directory:"
          find ./TestResults -name "*.opencover.xml" -type f || echo "No coverage files in TestResults"
          echo "In test project directories:"
          find ./OpenAutomate.*.Tests -name "*.opencover.xml" -type f || echo "No coverage files in test projects"
          echo "=== End of coverage files ==="
          
      # Generate HTML coverage report (only if coverage file exists)
      - name: Generate coverage report
        run: |
          if [ -f "./TestResults/coverage.opencover.xml" ]; then
            echo "Using coverage file: ./TestResults/coverage.opencover.xml"
            reportgenerator \
              -reports:./TestResults/coverage.opencover.xml \
              -targetdir:./TestResults/CoverageReport/Html \
              -reporttypes:Html \
              -assemblyfilters:"+OpenAutomate.API;+OpenAutomate.Core;+OpenAutomate.Infrastructure"
          else
            echo "Coverage file not found, skipping HTML report generation"
            # Create empty directory to avoid upload failure
            mkdir -p ./TestResults/CoverageReport/Html
          fi
          
          # Debug: Display coverage file contents to verify it's valid XML
          if [ -f "./TestResults/coverage.opencover.xml" ]; then
            echo "Validating coverage file format:"
            head -n 20 "./TestResults/coverage.opencover.xml"
          fi

      # Upload HTML report as artifact
      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-html
          path: ./TestResults/CoverageReport/Html
          retention-days: 5

      # Step 10: End SonarQube analysis
      - name: End SonarQube analysis
        run: |
          # Make sure coverage file is where SonarQube expects it
          if [ -f "./TestResults/coverage.opencover.xml" ]; then
            echo "Coverage file found at expected location"
          elif [ -f "./TestResults/CoverageReport/Opencover.xml" ]; then
            echo "Copying merged coverage file to expected location"
            cp "./TestResults/CoverageReport/Opencover.xml" "./TestResults/coverage.opencover.xml"
          else
            echo "Looking for any coverage files to use"
            # First check TestResults directory
            COVERAGE_FILES=$(find ./TestResults -name "*.opencover.xml" | head -1)
            if [ -n "$COVERAGE_FILES" ]; then
              echo "Using coverage file: $COVERAGE_FILES"
              cp "$COVERAGE_FILES" "./TestResults/coverage.opencover.xml"
            else
              # Then check test project root directories
              COVERAGE_FILES=$(find ./OpenAutomate.*.Tests -name "*.opencover.xml" | head -1)
              if [ -n "$COVERAGE_FILES" ]; then
                echo "Found coverage file in project directory: $COVERAGE_FILES"
                cp "$COVERAGE_FILES" "./TestResults/coverage.opencover.xml"
              else
                echo "WARNING: No coverage files found anywhere"
              fi
            fi
          fi
          
          # End SonarQube analysis
          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR decoration